import Footer from './components/footer/Footer'
import Header from './components/header/Header'
import './globals.css'


export const metadata = {
  title: '한국 ICT 인재 개발원',
  description: 'Generated by create hayeong',
  icons : {
    icon :'/images/ict_favicon.png'
  }
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
